channels:
  - defaults
  - conda-forge
  - bioconda

dependencies:
  - pip
  - lightning
  - tensorboard
  - biopython

### pynamod environments.yml ###
#
# name: pynamod
#
# channels:
#   - defaults
#   - conda-forge
#   - pip
#
# dependencies:
#   - python=3.13
#   - pip
#   - ipykernel
#   - mdanalysis
#   - pypdb
#   - numba
#   - nglview=3.1.4
#   - seaborn
#   - more-itertools
#   - pytest
#   - ipywidgets
#
#   - pip:
#       - --index-url https://download.pytorch.org/whl/cu130
#       - --extra-index-url https://pypi.org/simple
#       - torch
#       - torchvision
#       - pdb2pqr
