name: base2backbone

channels:
  - conda-forge

dependencies:
  - python=3.13.12
  - pip
  - gemmi
  - tensorboard
  - plotly
  - onnx

  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu129
      - --find-links https://data.pyg.org/whl/torch-2.8.0+cu129.html
      - torch==2.8.*
      - lightning
      - torch_geometric
