"""Shared geometry helpers with stable cross-module imports."""

from .backbone import (_BACKBONE_ATOM_ORDER, _BACKBONE_NAME_TO_INDEX,
                       _BRIDGE_NEXT_ATOM_ORDER, _BRIDGE_PREV_ATOM_ORDER,
                       _LOCAL_BACKBONE_ATOM_ORDER, _LOCAL_BACKBONE_INDEX,
                       _PHOSPHATE_ATOM_INDEX, _PHOSPHATE_ATOM_ORDER,
                       build_backbone_from_torsions,
                       build_backbone_from_torsions_torch,
                       build_batch_window_backbone_from_torsions_torch,
                       build_chain_backbone_from_predictions,
                       build_window_backbone_from_torsions_torch)
from .primitives import (GEO_EPS, GEO_EPS_NP, bond_angle_numpy,
                         bond_angle_torch, dihedral_rad, dihedral_rad_torch,
                         expand_point_frame, expand_point_origin,
                         local_to_world_points, local_to_world_torch,
                         nerf_place, nerf_place_torch,
                         orthonormal_basis_from_axis,
                         rodrigues_rotate_point_torch, safe_normalize,
                         signed_tetra_volume, world_to_local_points,
                         world_to_local_torch, wrap_angle_rad,
                         wrap_dihedral_diff_torch)
from .templates import get_template, get_template_tau_m, get_template_tensors
from .torsions import (RING_TORSION_DEFS, nucleotide_torsions_numpy,
                       nus_rad_from_P_tau_torch, pseudorotation_P_rad_from_nus,
                       pseudorotation_to_nus_torch, pucker_amplitude_rad,
                       sugar_ring_torsions_torch)

__all__ = [
    '_BACKBONE_ATOM_ORDER',
    '_BACKBONE_NAME_TO_INDEX',
    '_BRIDGE_NEXT_ATOM_ORDER',
    '_BRIDGE_PREV_ATOM_ORDER',
    '_LOCAL_BACKBONE_ATOM_ORDER',
    '_LOCAL_BACKBONE_INDEX',
    '_PHOSPHATE_ATOM_INDEX',
    '_PHOSPHATE_ATOM_ORDER',
    'GEO_EPS',
    'GEO_EPS_NP',
    'RING_TORSION_DEFS',
    'bond_angle_numpy',
    'bond_angle_torch',
    'dihedral_rad',
    'dihedral_rad_torch',
    'expand_point_frame',
    'expand_point_origin',
    'get_template',
    'get_template_tau_m',
    'get_template_tensors',
    'build_backbone_from_torsions',
    'build_backbone_from_torsions_torch',
    'build_batch_window_backbone_from_torsions_torch',
    'build_chain_backbone_from_predictions',
    'build_window_backbone_from_torsions_torch',
    'local_to_world_points',
    'local_to_world_torch',
    'nerf_place',
    'nerf_place_torch',
    'nucleotide_torsions_numpy',
    'nus_rad_from_P_tau_torch',
    'orthonormal_basis_from_axis',
    'pseudorotation_P_rad_from_nus',
    'pseudorotation_to_nus_torch',
    'pucker_amplitude_rad',
    'rodrigues_rotate_point_torch',
    'safe_normalize',
    'signed_tetra_volume',
    'sugar_ring_torsions_torch',
    'world_to_local_points',
    'world_to_local_torch',
    'wrap_angle_rad',
    'wrap_dihedral_diff_torch',
]
