BATCH_SIZE = 64
HIDDEN_DIM = 64
LR = 1e-3
NUM_EPOCHS = 50
NUM_TIMESTEPS = 200
WINDOW_SIZE = 3

# TODO: consider adding these features to the model
BOND_THRESHOLD = 1.9
SUPPORTED_EDGES = ['SINGLE', 'DOUBLE', 'TRIPLE', 'AROMATIC']
ATOMIC_NUMBERS = [6, 7, 8, 15, 16]
