name: Tests

on:
  workflow_dispatch:
  push: &test_paths
    branches:
      - main
      - master
    paths:
      - src/**
      - tests/**
      - environment.yml
      - pynamod/environment.yml
      - pyproject.toml
      - .github/workflows/tests.yml
  pull_request: *test_paths

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout base2backbone
        uses: actions/checkout@v5

      - name: Checkout PyNAMod
        uses: actions/checkout@v5
        with:
          repository: intbio/PyNAMod
          path: pynamod

      - name: Create environment with PyNAMod dependencies
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: pynamod/environment.yml
          environment-name: base2backbone
          cache-environment: false
          cache-downloads: true
          cache-downloads-key: conda-${{ hashFiles('environment.yml', 'pynamod/environment.yml', '.github/workflows/tests.yml') }}
          generate-run-shell: false

      - name: Update environment with project dependencies
        shell: bash -el {0}
        run: |
          micromamba env update \
              -n base2backbone \
              -f environment.yml

      - name: Cache pip downloads
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: >-
            pip-${{ runner.os }}-${{ hashFiles(
              'pyproject.toml',
              'environment.yml',
              'pynamod/environment.yml',
              '.github/workflows/tests.yml'
            ) }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install editable packages
        shell: bash -el {0}
        run: |
          micromamba run -n base2backbone \
              pip install -U pip
          micromamba run -n base2backbone \
              pip install -e '.[test]' -e ./pynamod

      - name: Run pytest
        shell: bash -el {0}
        run: |
          micromamba run -n base2backbone pytest tests
